# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 908a4e7b00ec2d718a1c66e1993272010b81edab5070203322a212f3405b1558627138e31404e66701c40660f51eee86ab3b2ce9c8da15e49aa7b0dc155c602d

test:
  secret_key_base: 03e61edd33a4201b465acb882791917913d055e8d3e85b9a29b6fdf7727ec2e8d5f7382d0a3d35ed807d37ed4b213d5c5c1e804a54e73798d2090c91ad79faa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
